### ISSUE TITLE
FEATURE: Submit a Poll Response

### ISSUE THREAD

**Issue by GrantWils23** [GrantWils23/love_running_project#1]
## USER STORY 1:
In order to **provide my opinion with regards to a certain running topic or event** as a **user**, I can **select and submit an answer to a poll**.

### Acceptance Criteria:
- The poll is accessed via a button.
- The poll opens up a form section as a pop-up display that shadows the background.
- The poll should clearly display the question of what the poll is about.
- The question should have an appropriate form type for the type of question. (i.e. Checkbox)
- The box will have a submit answer button at the end of the form.
- The answer can be sent to a database where the results are stored.

### Task:
- [ ] Create a button for the home display for the form section
- [ ] Create a pop-up window with shadowing for the form inside the display.
- [ ] Create a form section in the HTML file and appropriate styling in CSS.
- [ ] Create the appropriate question and form type for the question.
- [ ] At the bottom of the form create a submit answer button.

## USER STORY 2:
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**.

### Acceptance Criteria:
- The option should be provided as a checkbox.
- The checkbox should be "checked" by default.
- The option should appear next to the submit button.
-  After submitting the default submission, confirmation should be adjusted to include the user name.

### Task:
- [ ] Create a form-section
- [ ] Inside the form section, create a check-box
- [ ] Set its "default" to checked, 
- [ ] The checkbox should sit next to the submit button
- [ ] Upon submission, the user name or anonymous user will appear on the submission confirmation page.

## USER STORY 3:
In order to **provide additional thoughts beyond the response options** as a **user**, I can **add a comment before I submit my poll response**.

### Acceptance Criteria:
- Just above the submit answer button at the bottom of the screen, you can add a comment inside a text box by a specified size.
- The max amount of characters in this box does not exceed 300 words.
- The size of the box must be a rectangle shape.

### Task:
- [ ] Add an HTML form section "Text-area" next to the submit answer button.
- [ ] The size of the box must meet the acceptance criteria above.
